# Generated by Django 5.2.13 on 2026-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedProduct',
            fields=[
            ],
            options={
                'verbose_name': 'محصول حذف\u200cشده',
                'verbose_name_plural': 'محصولات حذف\u200cشده',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pharmacy.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
