# Generated by Django 5.2.13 on 2026-05-06 22:24

import pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_deletedproduct_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='profile_image',
            # خط زیر اصلاح شده است: default حذف شده
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
