# Generated by Django 5.2.13 on 2026-06-03 00:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_category_options_alter_pharmacyuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='نسخه')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش داده شود')),
                ('requires_confirm', models.BooleanField(default=False, verbose_name='نیاز به تأیید')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'به\u200cروزرسانی سیستم',
                'verbose_name_plural': 'به\u200cروزرسانی\u200cهای سیستم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='account_type',
            field=models.CharField(choices=[('admin', 'مدیر کل'), ('staff', 'پرسنل'), ('pharmacist', 'داروساز'), ('chemist', 'شیمی\u200cدان'), ('accountant', 'حسابدار'), ('doctor', 'دکتر')], default='staff', max_length=20, verbose_name='نوع حساب'),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='avatar_type',
            field=models.CharField(choices=[('doctor', 'دکتر'), ('pharmacist', 'داروساز'), ('chemist', 'شیمی\u200cدان'), ('accountant', 'حسابدار'), ('staff', 'پرسنل'), ('custom', 'عکس شخصی')], default='staff', max_length=20, verbose_name='نوع آواتار'),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='آنلاین'),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بازدید'),
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='pharmacy_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام داروخانه'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن اعلان')),
                ('notif_type', models.CharField(choices=[('info', 'اطلاع\u200cرسانی'), ('warning', 'هشدار'), ('success', 'موفقیت'), ('update', 'به\u200cروزرسانی'), ('urgent', 'فوری')], default='info', max_length=20, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر هدف (خالی = همه)')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تیکت')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('open', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='عملیات')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='مسیر بازدید')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فعالیت کاربر',
                'verbose_name_plural': 'فعالیت\u200cهای کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='pharmacy.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان خوانده\u200cشده',
                'verbose_name_plural': 'اعلانات خوانده\u200cشده',
                'unique_together': {('user', 'notification')},
            },
        ),
        migrations.CreateModel(
            name='UpdateConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirms', to='pharmacy.systemupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_confirms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تأیید به\u200cروزرسانی',
                'verbose_name_plural': 'تأییدیه\u200cهای به\u200cروزرسانی',
                'unique_together': {('user', 'update')},
            },
        ),
    ]
