# Generated by Django 5.2.13 on 2026-06-10 00:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_systemupdate_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی')),
                ('icon', models.CharField(choices=[('pill', '💊 قرص / کپسول'), ('syringe', '💉 آمپول / تزریقی'), ('bottle', '🧴 شربت / قطره'), ('tube', '🟡 پماد / کرم / ژل'), ('supplement', '🌿 مکمل / ویتامین'), ('bandage', '🩹 پانسمان / زخم'), ('hygiene', '🧼 بهداشتی'), ('cosmetic', '💄 آرایشی'), ('sexual', '❤️ سلامت جنسی'), ('orthopedic', '🦴 ارتوپدی / فیزیوتراپی'), ('eye', '👁 چشم / گوش / بینی'), ('baby', '👶 کودک / نوزاد'), ('herbal', '🌱 گیاهی / طبیعی'), ('device', '🩺 تجهیزات پزشکی'), ('other', '📦 سایر')], default='other', max_length=20, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته دارویی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای دارویی',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='systemupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='systemupdate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نمایش'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='path',
            field=models.CharField(blank=True, max_length=500, verbose_name='مسیر'),
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=300, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='نام انگلیسی / ژنریک')),
                ('brand_name', models.CharField(blank=True, max_length=300, verbose_name='نام تجاری / برند')),
                ('drug_form', models.CharField(choices=[('tablet', 'قرص'), ('capsule', 'کپسول'), ('syrup', 'شربت'), ('drop', 'قطره'), ('injection', 'آمپول / تزریقی'), ('serum', 'سرم'), ('ointment', 'پماد'), ('cream', 'کرم'), ('gel', 'ژل'), ('spray', 'اسپری'), ('inhaler', 'اینهالر'), ('patch', 'پچ / چسب'), ('suppository', 'شیاف'), ('powder', 'پودر'), ('solution', 'محلول'), ('lotion', 'لوسیون'), ('shampoo', 'شامپو'), ('soap', 'صابون'), ('device', 'دستگاه / تجهیزات'), ('bandage', 'باند / گاز / پانسمان'), ('other', 'سایر')], default='tablet', max_length=20, verbose_name='فرم دارو')),
                ('otc_rx', models.CharField(choices=[('otc', 'بدون نسخه (OTC)'), ('rx', 'نیاز به نسخه (Rx)'), ('na', 'غیر دارویی')], default='otc', max_length=5, verbose_name='نسخه\u200cای / بدون نسخه')),
                ('active_ingredient', models.CharField(blank=True, max_length=500, verbose_name='ماده مؤثره')),
                ('strength', models.CharField(blank=True, max_length=100, verbose_name='دوز / قدرت (مثلاً ۵۰۰mg)')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='تولیدکننده')),
                ('country_of_origin', models.CharField(blank=True, default='ایران', max_length=100, verbose_name='کشور سازنده')),
                ('indications', models.TextField(blank=True, help_text='مثال: سردرد، تب، درد، التهاب، عفونت باکتریایی', verbose_name='موارد مصرف / علائمی که برای آن تجویز می\u200cشود')),
                ('drug_class', models.CharField(blank=True, help_text='مثال: آنتی\u200cبیوتیک، NSAID، بتابلاکر، بنزودیازپین', max_length=200, verbose_name='خانواده دارویی')),
                ('contraindications', models.TextField(blank=True, verbose_name='موارد منع مصرف')),
                ('side_effects', models.TextField(blank=True, verbose_name='عوارض جانبی')),
                ('interactions', models.TextField(blank=True, verbose_name='تداخلات دارویی')),
                ('storage', models.CharField(blank=True, max_length=200, verbose_name='شرایط نگهداری')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات تکمیلی')),
                ('search_keywords', models.TextField(blank=True, help_text='کلماتی که کاربر ممکن است با آن جستجو کند — جدا با ویرگول', verbose_name='کلمات کلیدی جستجو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده توسط متخصص')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_drugs', to=settings.AUTH_USER_MODEL, verbose_name='افزوده توسط')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='pharmacy.drugcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
                'ordering': ['name_fa'],
                'indexes': [models.Index(fields=['name_fa'], name='pharmacy_dr_name_fa_b064a0_idx'), models.Index(fields=['name_en'], name='pharmacy_dr_name_en_13a509_idx'), models.Index(fields=['drug_class'], name='pharmacy_dr_drug_cl_e54374_idx'), models.Index(fields=['category'], name='pharmacy_dr_categor_c679fd_idx'), models.Index(fields=['is_active'], name='pharmacy_dr_is_acti_121d39_idx')],
            },
        ),
    ]
